# Programación 201

Librerías científicas en Python: `NumPy`
------------------------------------------------------

### Ejercicio 1
Calculad la norma y el determinante de la siguiente matriz: ```[[1, 0], [2, -1]]```.

In [2]:
# Respuesta
import numpy as np #importo la librería

Matriz = [[1, 0], [2, -1]]

np.linalg.det(Matriz)
np.linalg.norm(Matriz)
# Fuente: https://pybonacci.org/2012/06/07/algebra-lineal-en-python-con-numpy-i-operaciones-basicas/ 

2.449489742783178

### Ejercicio 2 
Evaluad las funciones arcoseno y arcocoseno en el intervalo [0,1] y con paso (resolución) de 0.1 y guardadlas en dos _arrays_.

In [5]:
# Respuesta

arcocoseno = np.arccos(np.arange(0,1,0.1)) #la función del acocoseno es arccos
arcocoseno
arcoseno = np.arcsin(np.arange(0,1,0.1)) # la del acoseno es arcsin
arcoseno

array([0.        , 0.10016742, 0.20135792, 0.30469265, 0.41151685,
       0.52359878, 0.64350111, 0.7753975 , 0.92729522, 1.11976951])

### Ejercicio 3
Generad una lista de 100 valores enteros aleatorios de 0-9. Realizad los siguientes cálculos utilizando métodos de _numpy_:
- Media y desviación estándar de los valores de la lista
- Valor máximo y mínimo
- Sumad todos los valores de la lista
- Conseguid una lista de valores únicos

In [6]:
# Respuesta
import random
lista = [] # primera forma de hacerlo con un for
for i in range(0,100): # le digo que recorra un rango de  0 a 100
    numero = random.randint(0,9) # por cada posición en el rango, asigne un numero aleatorio, función ranfom.randit, entre el 0 y el 9
    lista.append(numero) # cada valor asignado, me lo mete en una lista. 
len(lista)

lista = [random.randint(0,9) for i in range(0,100)] # Segunda forma de hacerlo. Usando una list comprehension. Es igual que la anterior pero más simple. 
lista = np.array(lista)
print(lista)

Media = np.mean(lista)
print(Media)
Desviaciontip = np.std(lista)
print(Desviaciontip)
maximo = np.max(lista)
print(maximo)
minimo = np.min(lista)
print(minimo)
suma = np.sum(lista)
print(suma)
unicos = np.unique(lista)
unicos

[3 8 6 2 4 9 5 4 3 1 6 0 7 4 9 5 9 9 6 5 8 3 7 5 0 7 8 3 3 2 4 0 1 5 8 0 2
 8 6 2 1 5 1 9 0 1 3 2 6 9 2 6 9 1 5 2 8 2 2 0 2 2 7 4 5 5 7 5 0 0 0 4 4 1
 5 3 5 7 2 9 6 0 0 6 3 9 1 4 0 9 6 3 9 1 9 3 5 5 0 8]
4.25
2.92702921065028
9
0
425


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Ejercicio 4
Ordenad la matriz bidimensional ```[[5,1,7], [0,7,4], [7,23,1]]``` por filas utilizando como algoritmo de ordenación el [Merge sort](https://en.wikipedia.org/wiki/Merge_sort).

**Hint:** No es necesario que implementéis el algoritmo de ordenación a mano, NumPy contiene métodos para realizar diferentes tipos de ordenación sobre diferentes estructuras de datos.

In [7]:
# Respuesta

matriz2 = np.array([[5,1,7], [0,7,4], [7,23,1]])
matriz2
print(np.sort(matriz2)) # la función sort ordena los valores de cada matriz. Pero estoy seguro que sea la forma correcta que se pide. 

[[ 1  5  7]
 [ 0  4  7]
 [ 1  7 23]]


In [8]:
print(np.sort(matriz2, None)) # Si introducimos el valro None, lo que hace es aplanar la matriz. 

[ 0  1  1  4  5  7  7  7 23]


### Ejercicio 5
Definid una función que dadas dos matrices, devuelva el valor absoluto de la multiplicación de los determinantes ambas, es decir, dadas A y B, nuestra función devolverá `|det(A) * det(B)|`.

In [8]:
# Respuesta

def producto_determinantes(A,B): # defino una función que multiplica los determinantes de dos matrices. 
    determinante_A = np.linalg.det(A) # la función linalg.det calcula el determinante de una matriz Fuente:https://stackoverrun.com/es/q/68017
    determinante_B = np.linalg.det(B)
    return abs(determinante_A * determinante_B) # con naumpy se puede usar también np.absolute() https://numpy.org/doc/stable/reference/generated/numpy.absolute.html

matriz_a = np.array([[2,-3],[-4,5]]) # lo compruebo con dos matrices cualquiera. 
matriz_b = np.array([[1,0],[2,-1]])     
producto_determinantes(matriz_a, matriz_b)


2.0

### Ejercicio 6
Cread una matriz 10x10 que corresponda con la [matriz identidad](https://es.wikipedia.org/wiki/Matriz_identidad) usando generadores básicos de arrays. Cread una matriz identidad 10x10 (esta vez usando generadores especificos de matrices identidad) y comprobad que ambas matrices son iguales

**Consideraciones**:
- La primera matriz debe crearse usando constructores básicos de arrays, como los presentados en los Notebooks de teoría.
* La segunda matriz debe generarse utilizando el generador de matrices identidad de numpy.
* La comparación debe devolver True si las matrices son iguales (un único True), False de no ser así.

In [10]:
# Respuesta
matriz_identidad = np.zeros(10*10).reshape(10,10) # así creo la matriz 10*10 con 0
matriz_identidad
for i in range(0,10):
    matriz_identidad[i][i] = 1 # Genero un for que recorra la matriz en su diagonal y sustituya los valores 0 por 1
matriz_identidad   

identidad_numpy = np.identity(10) # con la función np.identity creo la matriz unidad 10*10 de numpy

id(matriz_identidad)
id(identidad_numpy)

comprobacion = np.equal(matriz_identidad,identidad_numpy) # la comprobación de que sean iguales la hago en dos pasos. Primero creo una matriz que compara elemento por elemento si son iguales y devuelve true o false. Debería generar una matriz de Trues
comprobacion.all() # despues con .all() compruebo que todos los elementos de la matriz sean iguales, Si son todos trues me devuelve true y demuestra que son iguales las matrices matriz_identidad y identidad_numpy

True

### Ejercicio 7
Cread una matriz de 2x6 donde los valores de cada posición `(i, j)` correspondan a `i^2+j` para todo `i` par, `i/j^2` para todo `i` impar.

In [11]:
# Respuesta

matriz2x6 = np.arange(2*6).reshape(2,6) # Genero la matriz de 2x6

for i in range(matriz2x6.shape[0]): # ejecuto un for doble que recorra primero las filas i y despues de las columnas j
    for j in range(matriz2x6.shape[1]):
        if i%2 == 0: # Con un if evaluo si es par o impar. En este caso Cogerá como par solo la primera fila (valor 0) y ejecuja la siguiente operación i^2+j
            matriz2x6[i][j] = i**2+j
        else: # si no es par, ejecuta i/j**2. He añadido un try -except porque para el valor j = 0 da un error en la división, entonces en ese caso le digo que ponga el valor 0
            try:
                matriz2x6[i][j] = i/j**2
            except:
                matriz2x6[i][j] = 0

matriz2x6



array([[0, 1, 2, 3, 4, 5],
       [0, 1, 0, 0, 0, 0]])

### Ejercicio 8
Cread dos matrices de tamaño 5x5 con números reales aleatorios. Obtened el resultado de multiplicar ambas matrices usando los dos métodos de multiplicación de matrices vistos en el Notebook de teoría. ¿Cuál es la diferencia entre ambos resultados? Cread ahora dos matrices de tamaño 4x5 y 5x5 respectivamente, repetid la operación. Describid cuál de los métodos de multiplicación podéis aplicar y porqué

In [64]:
# Respuesta

matriz_random1 = [random.randint(0,9) for i in range(0,25)] # Creo la matriz con numeros del 0 al 9  por simplificar. 
matriz_random1 = np.array(matriz_random1).reshape(5,5)
print(matriz_random1)

matriz_random2 = [random.randint(0,9) for i in range(0,25)] # Creo la matriz con numeros del 0 al 9  por simplificar. 
matriz_random2 = np.array(matriz_random2).reshape(5,5)
print(matriz_random2)

[[3 7 8 9 8]
 [9 0 1 3 4]
 [8 1 6 4 4]
 [7 1 1 7 5]
 [3 2 2 0 7]]
[[1 9 4 3 9]
 [6 2 1 4 1]
 [3 3 1 6 0]
 [5 0 0 0 7]
 [5 2 9 8 8]]


In [66]:
multiplicada1 = matriz_random1*matriz_random2 # Este metodo lo que hace es multiplicar cada posición de la primera matriz por la misma posición de la segunda matriz. 
print(multiplicada1)
multiplicada2 = matriz_random1.dot(matriz_random2) # Este método hace la multiplicación matricial tradicional. El resultado de cada celda corresponde a la suma de la multiplicación de cada fila de la primera matriz por los valores de la columna de la segunda matriz. Por ejemplo, el valor 154 es resultado de sumar las multiplicaciones de los valores de la primera fila de la primera matriz por los valores de la primera columna de la segunda matriz, 154 =  3*1+7*6+8*3+9*5+8*5.
print(multiplicada2)

[[ 3 63 32 27 72]
 [54  0  1 12  4]
 [24  3  6 24  0]
 [35  0  0  0 35]
 [15  4 18  0 56]]
[[154  81  99 149 161]
 [ 47  92  73  65 134]
 [ 72 100  75  96 133]
 [ 76  78  75  71 153]
 [ 56  51  79  85  85]]


In [74]:

matriz_random3 = [random.randint(0,9) for i in range(0,20)] # Creo la matriz con numeros del 0 al 9  por simplificar. 
matriz_random3 = np.array(matriz_random3).reshape(4,5)
print(matriz_random3)

matriz_random4 = [random.randint(0,9) for i in range(0,25)] # Creo la matriz con numeros del 0 al 9  por simplificar. 
matriz_random4 = np.array(matriz_random4).reshape(5,5)
print(matriz_random4)

#multiplicada3 = matriz_random3*matriz_random4  # Este tipo da error porque las dimensiones de las matrices a multiplicar deben ser iguales. 
#print(multiplicada3)
multiplicada4 = matriz_random3.dot(matriz_random4) # hay que aplicar este tipo de multiplicación. Para que no de error tampoco este tipo de multiplicación, el número de columnas de la primera matriz debe ser igual que el numero de filas de la seunda matriz. 
print(multiplicada4)

[[0 4 9 7 4]
 [9 8 9 0 3]
 [0 7 0 8 2]
 [7 3 9 7 0]]
[[0 4 5 3 7]
 [2 5 8 0 7]
 [3 0 3 5 3]
 [6 8 1 2 9]
 [8 0 8 8 1]]
[[109  76  98  91 122]
 [ 67  76 160  96 149]
 [ 78  99  80  32 123]
 [ 75  99  93  80 160]]
